CREATE TABLE match (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    teamA VARCHAR(255) NOT NULL,
    teamB VARCHAR(255) NOT NULL,
    venue VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL
);